/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anna' at '10/28/15 2:46 PM' with Gradle 2.8
 *
 * @author anna, @date 10/28/15 2:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
